steps:
- script: dotnet build Pty.Net.sln --no-restore -c $(BuildConfiguration) /v:m /bl:"$(Build.ArtifactStagingDirectory)/build_logs/build.binlog"
  displayName: dotnet build
  workingDirectory: src

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: test
    arguments: --no-build -c $(BuildConfiguration) -v n /p:CollectCoverage=true
    testRunTitle: netcoreapp2.2-$(Agent.JobName)
    workingDirectory: src